spring.application.name=StorySurf

# Server Configuration
server.port=8080

# # Database Configuration (H2 for development)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB:storysurf}
spring.datasource.username=${POSTGRES_USER:storysurf_user}
spring.datasource.password=${POSTGRES_PASSWORD:storysurf123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true


# JPA/Hibernate Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console (for development only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
app.jwt.secret=mySecretKey123456789012345678901234567890
app.jwt.expiration=86400000


